# permissions for end users to view fscproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fscproxy-viewer-role
rules:
- apiGroups:
  - fsc.henderiw.be
  resources:
  - fscproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fsc.henderiw.be
  resources:
  - fscproxies/status
  verbs:
  - get
