# permissions for end users to edit fscproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fscproxy-editor-role
rules:
- apiGroups:
  - fsc.henderiw.be
  resources:
  - fscproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fsc.henderiw.be
  resources:
  - fscproxies/status
  verbs:
  - get
